const IS_LOGGED_IN = 'IS_LOGGED_IN';
const LOGIN_FAILED = 'LOGIN_FAILED';
const LOGIN_CALL = 'LOGIN_CALL';


const CHANGE_LANG = "CHANGE_LANG";
const UPDATE_FAVOURITE = "UPDATE_FAVOURITE";
const GET_FAVOURITE_LIST = "GET_FAVOURITE_LIST";
const PROFILE_UPDATE = "PROFILE_UPDATE";
const CHANGE_CONNECTION = "CHANGE_CONNECTION";

export const accountActions = {
    LOGIN_CALL,
    IS_LOGGED_IN,
    LOGIN_FAILED,
    CHANGE_LANG,
    UPDATE_FAVOURITE,
    GET_FAVOURITE_LIST,
    PROFILE_UPDATE,
    CHANGE_CONNECTION,
};
